<?php
/**
 * Created by PhpStorm.
 * User: nobita
 * Date: 1/17
 * Time: 16:05
 */

namespace app\admin\controller;

use think\Session;
use app\common\model\Setting as SettingModel;
use app\common\model\Site as SiteModel;

class Setting extends Base
{
    protected $userResult;
    public function _initialize()
    {
        //read userinfo
        $this->userResult = Session::get('user');
        $session = $this->userResult['group'];
        if ($session !== 1){
            $this->redirect('/admin');
            return false;
        }
        return parent::_initialize(); // TODO: Change the autogenerated stub
    }

    public function index(){
        $siteData = SiteModel::all();
        $data = [];
        foreach ($siteData as $item){
            $data[$item['type']] = $item['value'];
        }
        //$settingData = json_decode($siteData,true);
        $this->assign([
            'title' => '网站设置',
            'nav_cur' => 'setting',
            'siteData' => json_decode($data['site_setting'],true),
            'siteEmail' => json_decode($data['site_email'],true)
        ]);
        return $this->fetch('/setting');
    }

    public function update(){
        $data = input('post.');
        if ($data['type'] == 'site_setting'){
            $result = SiteModel::where('type','site_setting')->update([
                'value' => json_encode($data)
            ]);
            if ($result){
                return $this->redirect('/admin/setting');
            }else{
                return $this->redirect('/admin/setting');
            }
        }
        if ($data['type'] == 'site_email'){
            $result = SiteModel::where('type','site_email')->update([
                'value' => json_encode($data)
            ]);
            if ($result){
                return $this->redirect('/admin/setting');
            }else{
                return $this->redirect('/admin/setting');
            }
        }

    }
}